import { CategoryConfig } from "@databiosphere/findable-ui/lib/common/categories/config/types";
import { GA2_CATEGORY_KEY, GA2_CATEGORY_LABEL } from "../../../../category";

export const ACCESSION: CategoryConfig = {
  key: GA2_CATEGORY_KEY.ACCESSION,
  label: GA2_CATEGORY_LABEL.ACCESSION,
};

export const ANNOTATION_STATUS: CategoryConfig = {
  key: GA2_CATEGORY_KEY.ANNOTATION_STATUS,
  label: GA2_CATEGORY_LABEL.ANNOTATION_STATUS,
};

export const ASSEMBLY_TAXONOMY_IDS: CategoryConfig = {
  key: GA2_CATEGORY_KEY.ASSEMBLY_TAXONOMY_IDS,
  label: GA2_CATEGORY_LABEL.ASSEMBLY_TAXONOMY_IDS,
};

export const COVERAGE: CategoryConfig = {
  key: GA2_CATEGORY_KEY.COVERAGE,
  label: GA2_CATEGORY_LABEL.COVERAGE,
};

export const IS_REF: CategoryConfig = {
  key: GA2_CATEGORY_KEY.IS_REF,
  label: GA2_CATEGORY_LABEL.IS_REF,
};

export const LEVEL: CategoryConfig = {
  key: GA2_CATEGORY_KEY.LEVEL,
  label: GA2_CATEGORY_LABEL.LEVEL,
};

export const TAXONOMIC_GROUP: CategoryConfig = {
  key: GA2_CATEGORY_KEY.TAXONOMIC_GROUP,
  label: GA2_CATEGORY_LABEL.TAXONOMIC_GROUP,
};

export const TAXONOMIC_LEVEL_DOMAIN: CategoryConfig = {
  key: GA2_CATEGORY_KEY.TAXONOMIC_LEVEL_DOMAIN,
  label: GA2_CATEGORY_LABEL.TAXONOMIC_LEVEL_DOMAIN,
};

export const TAXONOMIC_LEVEL_KINGDOM: CategoryConfig = {
  key: GA2_CATEGORY_KEY.TAXONOMIC_LEVEL_KINGDOM,
  label: GA2_CATEGORY_LABEL.TAXONOMIC_LEVEL_KINGDOM,
};

export const TAXONOMIC_LEVEL_PHYLUM: CategoryConfig = {
  key: GA2_CATEGORY_KEY.TAXONOMIC_LEVEL_PHYLUM,
  label: GA2_CATEGORY_LABEL.TAXONOMIC_LEVEL_PHYLUM,
};

export const TAXONOMIC_LEVEL_CLASS: CategoryConfig = {
  key: GA2_CATEGORY_KEY.TAXONOMIC_LEVEL_CLASS,
  label: GA2_CATEGORY_LABEL.TAXONOMIC_LEVEL_CLASS,
};

export const TAXONOMIC_LEVEL_ORDER: CategoryConfig = {
  key: GA2_CATEGORY_KEY.TAXONOMIC_LEVEL_ORDER,
  label: GA2_CATEGORY_LABEL.TAXONOMIC_LEVEL_ORDER,
};

export const TAXONOMIC_LEVEL_FAMILY: CategoryConfig = {
  key: GA2_CATEGORY_KEY.TAXONOMIC_LEVEL_FAMILY,
  label: GA2_CATEGORY_LABEL.TAXONOMIC_LEVEL_FAMILY,
};

export const TAXONOMIC_LEVEL_GENUS: CategoryConfig = {
  key: GA2_CATEGORY_KEY.TAXONOMIC_LEVEL_GENUS,
  label: GA2_CATEGORY_LABEL.TAXONOMIC_LEVEL_GENUS,
};

export const TAXONOMIC_LEVEL_SPECIES: CategoryConfig = {
  key: GA2_CATEGORY_KEY.TAXONOMIC_LEVEL_SPECIES,
  label: GA2_CATEGORY_LABEL.TAXONOMIC_LEVEL_SPECIES,
};

export const TAXONOMIC_LEVEL_STRAIN: CategoryConfig = {
  key: GA2_CATEGORY_KEY.TAXONOMIC_LEVEL_STRAIN,
  label: GA2_CATEGORY_LABEL.TAXONOMIC_LEVEL_STRAIN,
};

export const TAXONOMY_ID: CategoryConfig = {
  key: GA2_CATEGORY_KEY.TAXONOMY_ID,
  label: GA2_CATEGORY_LABEL.TAXONOMY_ID,
};
