name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - "feat"
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "📝 Documentation"
    labels:
      - "docs"
      - "documentation"
  - title: "🧩 Content"
    label: "content"
  - title: "💄 Styles"
    label: "style"
  - title: "♻️ Code Refactoring"
    label: "refactor"
  - title: "⚡ Performance Improvements"
    label: "perf"
  - title: "✅ Tests"
    label: "test"
  - title: "🛠️ Build System"
    label: "build"
  - title: "👷 Continuous Integration"
    label: "ci"
  - title: "🧹 Chores"
    label: "chore"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"

change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

version-resolver:
  major:
    labels:
      - "major"
      - "breaking"
  minor:
    labels:
      - "minor"
      - "feat"
      - "feature"
      - "enhancement"
  patch:
    labels:
      - "patch"
      - "fix"
      - "bugfix"
      - "bug"
      - "docs"
      - "documentation"
      - "style"
      - "refactor"
      - "perf"
      - "test"
      - "build"
      - "ci"
      - "chore"
      - "content"
  default: patch

autolabeler:
  - label: "feat"
    title:
      - '/^feat(\(.+\))?:/i'
  - label: "fix"
    title:
      - '/^fix(\(.+\))?:/i'
  - label: "docs"
    title:
      - '/^docs(\(.+\))?:/i'
  - label: "style"
    title:
      - '/^style(\(.+\))?:/i'
  - label: "refactor"
    title:
      - '/^refactor(\(.+\))?:/i'
  - label: "perf"
    title:
      - '/^perf(\(.+\))?:/i'
  - label: "test"
    title:
      - '/^test(\(.+\))?:/i'
  - label: "build"
    title:
      - '/^build(\(.+\))?:/i'
  - label: "ci"
    title:
      - '/^ci(\(.+\))?:/i'
  - label: "chore"
    title:
      - '/^chore(\(.+\))?:/i'
  - label: "content"
    title:
      - '/^content(\(.+\))?:/i'
  - label: "breaking"
    title:
      - '/\!:/i'

template: |
  ## Changes in v$RESOLVED_VERSION

  $CHANGES

  **Full Changelog**: https://github.com/galaxyproject/brc-analytics/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
