import { SectionSubtitle, SectionTitle } from "../../../section.styles";
import { AnalyticsToolsAndData } from "./components/AnalyticsToolsAndData/analyticsToolsAndData";
import { Headline, Section, SectionLayout } from "./sectionAnalyticsAndData.styles";

export const SectionAnalyticsAndData = (): JSX.Element => {
  return (
    <Section>
      <SectionLayout>
        <Headline>
          <SectionTitle>What is GenomeArk Analytics?</SectionTitle>
          <SectionSubtitle>
            GenomeArk Analytics pairs official genomic data provided by the NCBI
            Datasets, generated by multiple project (EBP, VGP, T2T) and UCSC Genome Browser with unlimited analytical capacity
            of Galaxy Platform powered by the Texas Advanced Computing Center
            (TACC).
          </SectionSubtitle>
        </Headline>
        <AnalyticsToolsAndData />
      </SectionLayout>
    </Section>
  );
};
