export interface LoganExample {
  // Index divisions and library types the example is meant to run against,
  // in the picker's own codes.
  divisions: string[];
  key: string;
  label: string;
  // Where the sequence came from, in words, for the chip's tooltip.
  note: string;
  sequence: string;
  strategies: string[];
}

// Every sequence below is an NCBI nuccore range fetched with E-utilities
// (efetch, rettype=fasta, seq_start/seq_stop), never typed in or edited, so a
// hit list can be checked against the record it came from. The accession and
// range are in each FASTA header. Each is paired with the one index its
// organism lives in: an example should be a cheap first run, not the dearest.
export const LOGAN_EXAMPLES: LoganExample[] = [
  {
    divisions: ["INV"],
    key: "plasmodium-18s",
    label: "P. falciparum 18S",
    note: "M19172.1:601-1100, a 500 bp window of the Plasmodium falciparum 18S rRNA. Plasmodium sits in the invertebrate division, which carries all but a handful of this query's hits.",
    sequence: `>Plasmodium_falciparum_18S M19172.1:601-1100
GCGTATATTAAAATTGTTGCAGTTAAAACGCTCGTAGTTGAATTTCAAAGAATCGATATTTTATTGTAAC
TATTCTAGGGGAACTATTTTAGCTTTTGGCTTTAATACGCTTCCTCTATTATTATGTTCTTTAAATAACA
AAGATTCTTTTTAAAATCCCCACTTTTGCTTTTGCTTTTTTGGGGATTTTGTTACTTTGAGTAAATTAGA
GTGTTCAAAGCAAACAGTTAAAGCATTTACTGTGTTTGAATACTATAGCATGGAATAACAAAATTGAACA
AGCTAAAATTTTTTGTTCTTTTTTCTTATTTTGGCTTAGTTACGATTAATAGGAGTAGCTTGGGGACATT
CGTATTCAGATGTCAGAGGTGAAATTCTTAGATTTTCTGGAGACGAACAACTGCGAAAGCATTTGTCTAA
AATACTTCCATTAATCAAGAACGAAAGTTAAGGGAGTGAAGACGATCAGATACCGTCGTAATCTTAACCA
TAAACTATGC`,
    strategies: ["GENOMIC"],
  },
  {
    divisions: ["BCT"],
    key: "mtb-rpob",
    label: "M. tuberculosis rpoB",
    note: "NC_000962.3:760822-761421, 600 bp of M. tuberculosis H37Rv rpoB spanning the rifampicin resistance-determining region. Isolate sequencing is genomic runs in the bacterial division.",
    sequence: `>Mycobacterium_tuberculosis_rpoB NC_000962.3:760822-761421
TGGTCCGCTTGCACGAGGGTCAGACCACGATGACCGTTCCGGGCGGCGTCGAGGTGCCGGTGGAAACCGA
CGACATCGACCACTTCGGCAACCGCCGCCTGCGTACGGTCGGCGAGCTGATCCAAAACCAGATCCGGGTC
GGCATGTCGCGGATGGAGCGGGTGGTCCGGGAGCGGATGACCACCCAGGACGTGGAGGCGATCACACCGC
AGACGTTGATCAACATCCGGCCGGTGGTCGCCGCGATCAAGGAGTTCTTCGGCACCAGCCAGCTGAGCCA
ATTCATGGACCAGAACAACCCGCTGTCGGGGTTGACCCACAAGCGCCGACTGTCGGCGCTGGGGCCCGGC
GGTCTGTCACGTGAGCGTGCCGGGCTGGAGGTCCGCGACGTGCACCCGTCGCACTACGGCCGGATGTGCC
CGATCGAAACCCCTGAGGGGCCCAACATCGGTCTGATCGGCTCGCTGTCGGTGTACGCGCGGGTCAACCC
GTTCGGGTTCATCGAAACGCCGTACCGCAAGGTGGTCGACGGCGTGGTTAGCGACGAGATCGTGTACCTG
ACCGCCGACGAGGAGGACCGCCACGTGGTGGCACAGGCCA`,
    strategies: ["GENOMIC"],
  },
  {
    divisions: ["BCT"],
    key: "kpc-2",
    label: "Klebsiella blaKPC-2",
    note: "AY034847.1:6-887, the complete blaKPC-2 carbapenemase coding sequence from Klebsiella pneumoniae. The gene rides on plasmids, so hits reach well past Klebsiella.",
    sequence: `>Klebsiella_pneumoniae_blaKPC-2 AY034847.1:6-887
ATGTCACTGTATCGCCGTCTAGTTCTGCTGTCTTGTCTCTCATGGCCGCTGGCTGGCTTTTCTGCCACCG
CGCTGACCAACCTCGTCGCGGAACCATTCGCTAAACTCGAACAGGACTTTGGCGGCTCCATCGGTGTGTA
CGCGATGGATACCGGCTCAGGCGCAACTGTAAGTTACCGCGCTGAGGAGCGCTTCCCACTGTGCAGCTCA
TTCAAGGGCTTTCTTGCTGCCGCTGTGCTGGCTCGCAGCCAGCAGCAGGCCGGCTTGCTGGACACACCCA
TCCGTTACGGCAAAAATGCGCTGGTTCCGTGGTCACCCATCTCGGAAAAATATCTGACAACAGGCATGAC
GGTGGCGGAGCTGTCCGCGGCCGCCGTGCAATACAGTGATAACGCCGCCGCCAATTTGTTGCTGAAGGAG
TTGGGCGGCCCGGCCGGGCTGACGGCCTTCATGCGCTCTATCGGCGATACCACGTTCCGTCTGGACCGCT
GGGAGCTGGAGCTGAACTCCGCCATCCCAGGCGATGCGCGCGATACCTCATCGCCGCGCGCCGTGACGGA
AAGCTTACAAAAACTGACACTGGGCTCTGCACTGGCTGCGCCGCAGCGGCAGCAGTTTGTTGATTGGCTA
AAGGGAAACACGACCGGCAACCACCGCATCCGCGCGGCGGTGCCGGCAGACTGGGCAGTCGGAGACAAAA
CCGGAACCTGCGGAGTGTATGGCACGGCAAATGACTATGCCGTCGTCTGGCCCACTGGGCGCGCACCTAT
TGTGTTGGCCGTCTACACCCGGGCGCCTAACAAGGATGACAAGCACAGCGAGGCCGTCATCGCCGCTGCG
GCTAGACTCGCGCTCGAGGGATTGGGCGTCAACGGGCAGTAA`,
    strategies: ["GENOMIC"],
  },
  {
    divisions: ["VRL"],
    key: "mpox-f13l",
    label: "Mpox F13L",
    note: "NC_063383.1:39200-39799, 600 bp of the mpox virus F13L (OPG057) envelope protein gene, from the 2022 outbreak reference. A DNA virus, so whole-genome runs land in the genomic viral index.",
    sequence: `>Monkeypox_virus_F13L NC_063383.1:39200-39799
TCCGTCGAAATTTGCCGAAGTGATATGAACATATTCGTCGTCGACTATTAACAATTTTGTATTATTCTGA
ATAGTGAAAACCTTCACAGATAGATCATTTTGAACACACAACGCATCTAGACTTCTGGCGGTTGCCATAG
AATATACGTCGTTCTTATCCCAATTACCAACTAGAAGTCTGATCTTAACTCCTCTATTAATGGCTGCTTC
TATAATGGAGTTGTAAATGTCAGGCCAATAGTAGCTATTACCGTCGACACGTGTAGTGGGAACTATGGCC
AAATGTTCAATATCTATACTAGTCTTAGCCGACTTGAGTTTATCAATAACTACATCAGTGTCTAGATCTC
TAGAATATCCCAATAGGTGTTCTGGAGAATCAGTAAAGAACACTCCACCTATAGGATTCTTAATATGATA
CGCAGTGCTAACTGGCAGACAACAAGCCGCAGAGCATAAATTCAACCATGAATTTTTTGCGCTATTAAAG
GCTTTAAAAGTATCAAATCTTCTACGAAGATCTGTGGCCAGCGGAGGATAATCAGAATATACGCCTAACG
TTTTAATCGTATGTATAGATCCTCCAGTAAATGACGCGTT`,
    strategies: ["GENOMIC"],
  },
  {
    divisions: ["INV"],
    key: "aedes-cox1",
    label: "Aedes aegypti COI",
    note: "NC_035159.1:1340-1997, 658 bp of the Aedes aegypti mitochondrial COX1 gene, the barcoding end. Mosquito genomes are invertebrate genomic runs.",
    sequence: `>Aedes_aegypti_COX1 NC_035159.1:1340-1997
ACTTTATATTTCATTTTTGGAGTATGATCTGGAATAGTCGGAACTTCTCTAAGAATTTTAATTCGTGCTG
AACTTAGCCACCCTGGTATATTTATTGGGAATGACCAAATTTATAATGTAATTGTAACAGCTCATGCATT
TATTATAATTTTCTTTATAGTAATGCCAATTATAATTGGAGGATTTGGAAATTGATTAGTTCCTTTAATA
TTAGGAGCCCCTGATATAGCTTTCCCTCGAATGAATAATATAAGTTTTTGAATACTACCTCCTTCATTGA
CTCTTCTATTATCAAGCTCAATAGTAGAAAATGGGGCAGGAACTGGGTGAACAGTTTATCCTCCTCTCTC
TTCAGGAACAGCTCATGCTGGAGCTTCTGTTGATTTAGCTATTTTTTCTCTTCATTTAGCTGGAATTTCC
TCAATTTTAGGGGCAGTAAATTTTATTACAACTGTGATTAATATGTGATCGTCAGGGATTACTTTAGATC
GACTACCCTTATTTGTTTGATCTGTAGTTATTACAGCTATCTTATTACTTCTTTCTCTTCCTGTTTTAGC
TGGAGCTATTACTATATTATTAACAGACCGAAACTTAAATACATCTTTCTTTGATCCAATCGGAGGGGGA
GACCCTATTTTATACCAACACTTATTTT`,
    strategies: ["GENOMIC"],
  },
];
