export const ROUTES = {
  ABOUT: "/about",
  ANALYZE_WORKFLOWS: "/data/assemblies/{entityId}/analyze/workflows",
  ASSISTANT: "/assistant",
  CALENDAR: "/calendar",
  CONFIGURE_CUSTOM_WORKFLOW: "/data/assemblies/{entityId}/analyze/custom",
  CONFIGURE_WORKFLOW: "/data/assemblies/{entityId}/analyze/workflows/{trsId}",
  GENOME: "/data/assemblies/{entityId}",
  GENOMES: "/data/assemblies",
  LEARN: "/learn",
  ORGANISMS: "/data/organisms",
  PRIORITY_PATHOGEN: "/data/[entityListType]/[entityId]",
  PRIORITY_PATHOGENS: "/data/priority-pathogens",
  ROADMAP: "/roadmap",
  WORKFLOW: "/data/workflows/{trsId}",
  WORKFLOWS: "/data/workflows",
};
