import { Button } from "@mui/material";
import { Fragment } from "react";
import { ROUTES } from "../../../../../../../../routes/constants";
import { calculateGridSize } from "../../../../../../Layout/components/Hero/common/utils";
import { Carousel } from "./components/Carousel/carousel";
import { Hero } from "../../SectionHero/components/Hero/hero";
import { BUTTON_PROPS } from "../../SectionHero/constants";
import {
  Head,
  Headline,
  SectionLayout,
  StyledSection,
  Subhead,
  SubHeadline,
} from "./sectionHero.styles";

export const SectionHero = (): JSX.Element => {
  return (
    <StyledSection>
      {(height, width): JSX.Element => (
        <Fragment>
          <Hero
            gridSize={calculateGridSize(height)}
            height={height}
            width={width}
          />
          <SectionLayout>
            <Headline>
              <Head>
                <span>Analytics for Vertebrate Genomes </span>
                <span></span>
              </Head>
              <SubHeadline>
                <Subhead>
                  Comprehensive tools and workflows for downstream analysis of
                  vertebrate genomes data generated by <a href="https://www.earthbiogenome.org/" target="_blank" rel="noopener noreferrer">Earth BioGenome Project</a>,
                  the <a href="https://vertebrategenomesproject.org/" target="_blank" rel="noopener noreferrer">Vertebrate Genomes Project</a>,
                  the <a href="https://sites.google.com/ucsc.edu/t2tworkinggroup/home" target="_blank" rel="noopener noreferrer">Telomere-to-Telomere Consortium</a>
                  and other related projects.
                </Subhead>
                <Button {...BUTTON_PROPS} href={ROUTES.ORGANISMS}>
                  Get started
                </Button>
              </SubHeadline>
            </Headline>
            <Carousel />
          </SectionLayout>
        </Fragment>
      )}
    </StyledSection>
  );
};
