export enum SEQUENCING_DATA_TYPE {
  READ_RUNS_ANY = "readRunsAny",
  READ_RUNS_PAIRED = "readRunsPaired",
  READ_RUNS_PAIRED_FILE = "readRunPairedFile",
  READ_RUNS_SINGLE = "readRunsSingle",
  READ_RUNS_SINGLE_FILE = "readRunSingleFile",
}

export type SEQUENCING_DATA_FILE_TYPE =
  | SEQUENCING_DATA_TYPE.READ_RUNS_PAIRED
  | SEQUENCING_DATA_TYPE.READ_RUNS_PAIRED_FILE
  | SEQUENCING_DATA_TYPE.READ_RUNS_SINGLE
  | SEQUENCING_DATA_TYPE.READ_RUNS_SINGLE_FILE;

export const STEP_KEY_TO_LIBRARY_LAYOUT: Record<
  SEQUENCING_DATA_FILE_TYPE,
  string
> = {
  [SEQUENCING_DATA_TYPE.READ_RUNS_PAIRED]: "PAIRED",
  [SEQUENCING_DATA_TYPE.READ_RUNS_PAIRED_FILE]: "PAIRED",
  [SEQUENCING_DATA_TYPE.READ_RUNS_SINGLE]: "SINGLE",
  [SEQUENCING_DATA_TYPE.READ_RUNS_SINGLE_FILE]: "SINGLE",
};
