export type ClassificationMap = Map<string, COLUMN_TYPE | null>;

export type ColumnClassifications = Record<string, COLUMN_TYPE | null>;

export enum COLUMN_TYPE {
  BIOLOGICAL_FACTOR = "BIOLOGICAL_FACTOR",
  FORWARD_FILE_MD5 = "FORWARD_FILE_MD5",
  FORWARD_FILE_URL = "FORWARD_FILE_URL",
  IDENTIFIER = "IDENTIFIER",
  IGNORED = "IGNORED",
  OTHER_COVARIATE = "OTHER_COVARIATE",
  QC_ONLY = "QC_ONLY",
  REVERSE_FILE_MD5 = "REVERSE_FILE_MD5",
  REVERSE_FILE_URL = "REVERSE_FILE_URL",
  TECHNICAL_BLOCKING_FACTOR = "TECHNICAL_BLOCKING_FACTOR",
}
