export const GA2_CATEGORY_KEY = {
  ACCESSION: "accession",
  ANALYZE_GENOME: "analyzeGenome",
  ANNOTATION_STATUS: "annotationStatus",
  ASSEMBLY_COUNT: "assemblyCount",
  ASSEMBLY_TAXONOMY_IDS: "assemblyTaxonomyIds",
  CHROMOSOMES: "chromosomes",
  COVERAGE: "coverage",
  GC_PERCENT: "gcPercent",
  IS_REF: "isRef",
  LENGTH: "length",
  LEVEL: "level",
  SCAFFOLD_COUNT: "scaffoldCount",
  SCAFFOLD_L50: "scaffoldL50",
  SCAFFOLD_N50: "scaffoldN50",
  STRAIN_NAME: "strainName",
  TAXONOMIC_GROUP: "taxonomicGroup",
  TAXONOMIC_LEVEL_SPECIES: "taxonomicLevelSpecies",
  TAXONOMIC_LEVEL_STRAIN: "taxonomicLevelStrain",
  TAXONOMY_ID: "ncbiTaxonomyId",
};

export const GA2_CATEGORY_LABEL = {
  ACCESSION: "Accession",
  ANALYZE_GENOME: "Action",
  ANNOTATION_STATUS: "Annotation Status",
  ASSEMBLY_COUNT: "Assemblies",
  ASSEMBLY_TAXONOMY_IDS: "Taxonomy ID",
  CHROMOSOMES: "Chromosomes",
  COVERAGE: "Coverage",
  GC_PERCENT: "GC%",
  IS_REF: "Is Ref",
  LENGTH: "Length",
  LEVEL: "Level",
  SCAFFOLD_COUNT: "Scaffolds",
  SCAFFOLD_L50: "Scaffold L50",
  SCAFFOLD_N50: "Scaffold N50",
  STRAIN_NAME: "Strain Name",
  TAXONOMIC_GROUP: "Taxonomic Group",
  TAXONOMIC_LEVEL_SPECIES: "Species",
  TAXONOMIC_LEVEL_STRAIN: "Strain",
  TAXONOMY_ID: "Taxonomy ID",
};
