import { SEQUENCING_DATA_TYPE } from "../../../../types";
import { CATEGORY_CONFIGS } from "./hooks/UseTable/categoryConfigs";

export const PRESELECTED_COLUMN_FILTERS: Record<
  SEQUENCING_DATA_TYPE,
  Record<string, string[]>
> = {
  [SEQUENCING_DATA_TYPE.READ_RUNS_PAIRED]: {
    [CATEGORY_CONFIGS.LIBRARY_LAYOUT.key]: ["PAIRED"],
    [CATEGORY_CONFIGS.LIBRARY_STRATEGY.key]: ["WGS"],
  },
  [SEQUENCING_DATA_TYPE.READ_RUNS_SINGLE]: {
    [CATEGORY_CONFIGS.LIBRARY_LAYOUT.key]: ["SINGLE"],
    [CATEGORY_CONFIGS.LIBRARY_STRATEGY.key]: ["WGS"],
  },
};
