id: https://github.com/galaxyproject/brc-analytics/blob/main/catalog/schema/schema.yaml#
name: schema

prefixes:
  linkml: https://w3id.org/linkml/

imports:
  - ./assemblies
  - ./workflow_categories
  - ./workflows
