#!/bin/sh

echo '🏗️👷 Checking your project before committing'

# Check Prettier
npm run check-format ||
(
    echo '🤔 Prettier Check Failed. Run npx prettier --write . try commit again.';
    false;
)

# Check ESLint
npm run lint ||
(
        echo '🤔  ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false;
)

# Format Python files
echo '🐍 Formatting Python files with Ruff...'
npm run format:python

# Check TypeScript
npm run typecheck ||
(
	echo 'TypeScript compile failed';
	false;
)
echo 'TypeScript compile succeeded!'
