name: Release Drafter

on:
  push:
    branches:
      - main
  workflow_dispatch: # Enable manual triggering

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    if: github.repository == 'galaxyproject/brc-analytics'
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
